# Generated by Django 4.2.27 on 2026-01-30 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(help_text='Rating: 5=Highly characteristic, 4=Most of the time, 3=Frequently, 2=Occasionally, 1=Not at all', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
