# Generated by Django 4.2.27 on 2026-01-30 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_answer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
